### PR TITLE
When performing an update, available releases are listed in batches of 5

### PR DESCRIPTION
**Pull request by korijHT**
Users will see the 5 most recent release versions and can request 5 additional versions at a time by typing "more".
Added differentiation between standard display text and displayed data with the color green where it seemed useful to highlight available options for the user.

### CODE REVIEW

**Comment by Jjohns-Hypertherm** [comment]
I see you revised the phrase I had asked about. Thanks!

**Comment by richarda** [comment]
I noticed that the artifact is called:
image
`cli-cc.exe`, but the actual file that comes out after downloading and unzipping is `cc-cli.exe`. Is that something that should be changed?

**Comment by richarda** [comment]
Looks nice - I like the purple "more"!
image

**Comment by richarda** [comment]
I tried to downgrade and got this:
image
```Powershell
An unhandled exception has occurred: Cannot cast Newtonsoft.Json.Linq.JProperty to Newtonsoft.Json.Linq.JToken.
```

**Comment by korijHT** [comment]
> I tried to downgrade and got this:
> image
> 
> ```powershell
> An unhandled exception has occurred: Cannot cast Newtonsoft.Json.Linq.JProperty to Newtonsoft.Json.Linq.JToken.
> ```

@richarda Interesting, I will look into this. I had not seen that before.
Are you able to reproduce it everytime?

**Comment by korijHT** [comment]
> I noticed that the artifact is called:
> image
> `cli-cc.exe`, but the actual file that comes out after downloading and unzipping is `cc-cli.exe`. Is that something that should be changed?

@richarda, I will look at the GitHub Actions workflow and see if the typo is in there.

**Comment by korijHT** [comment]
Yea found it:
image

**Comment by richarda** [comment]
> > I tried to downgrade and got this:
> > image
> > ```powershell
> > An unhandled exception has occurred: Cannot cast Newtonsoft.Json.Linq.JProperty to Newtonsoft.Json.Linq.JToken.
> > ```
> 
> @richarda Interesting, I will look into this. I had not seen that before.
> Are you able to reproduce it everytime?

yes 😄 
image

**Comment by richarda** [comment]
The exception is gone now. I am able to do an update.
I wonder if you want to address these now or add some issues to the backlog:
- [ ] console text is changed/remains purple of you use "Ctrl-C" instead of "Enter" to cancel the update.
- [ ] It would be helpful to list the current version before "Available versions:"

**Comment by korijHT** [comment]
> The exception is gone now. I am able to do an update.
> I wonder if you want to address these now or add some issues to the backlog:
> 
> * [ ]  console text is changed/remains purple of you use "Ctrl-C" instead of "Enter" to cancel the update.
> * [ ]  It would be helpful to list the current version before "Available versions:"

@richarda 
Adding the current version print out when doing an update sounds good and is pretty simple to do.

As for the color, it should revert back after a line or two I believe.
"Ctrl+C" is similar to "Alt-F4" I believe. I will look into any hooks that would allow code to run as part of that shutdown path.

**Comment by korijHT** [comment]
@richarda 
Looks like there is a nice hook available.

Console.CancelKeyPress += delegate {
        // call methods to clean up
};

**Pull request merged**
